[ci]
runtime = "nix"
runner = "ubuntu-24.04"
workspace = true
provider = "actions"
platform = "github"
publish_crates = true
check_command = "harbor-ci full"
all_features = false

[ci.pages]
repo = "caniko/nix-cache-pin"
canonical_domain = "nix-cache-pin.tartanoglu.com"
