{sourcePinsSelf}: {
  lib,
  config,
  ...
}: let
  inherit
    (lib)
    types
    mapAttrs
    mapAttrsToList
    concatStringsSep
    escapeShellArg
    nameValuePair
    ;

  options = import ./options.nix {inherit lib;};
  extractors.cargo-git = import ./extractor.nix {inherit lib;};
in {
  options = options;

  config = let
    cfg = config.cache-pin.source-pins;

    computedPins = mapAttrs (name: pin:
      extractors.${pin.type}.compute pin.lockFile
    ) cfg;

    pinMeta = mapAttrs (_name: pin: {
      type = pin.type;
      lockFile = builtins.toString pin.lockFile;
      outputFile = pin.outputFile;
    }) cfg;
  in {
    flake.sourcePinsMeta = {
      schemaVersion = 1;
      pins = pinMeta;
    };

    flake.sourcePins = computedPins;

    perSystem = {
      pkgs,
      system,
      ...
    }: let
      jqBin = "${pkgs.jq}/bin/jq";
      nixBin = "${pkgs.nix}/bin/nix";

      mkUpdateScript = name: pin: let
        lockFileStorePath = builtins.toString pin.lockFile;
        outputFileRel = pin.outputFile;
      in
        pkgs.writeShellScriptBin "cache-pin-source-pins-${name}" ''
          set -euo pipefail

          n="${escapeShellArg name}"
          output_rel="${escapeShellArg outputFileRel}"
          lock="${escapeShellArg lockFileStorePath}"

          echo "=== cache-pin source-pins: $n ==="
          echo "  Lock file:  $lock"

          # nix run preserves cwd — use it as repo root
          repo_root="$(pwd)"
          output_file="$repo_root/$output_rel"

          echo "  Output:      $output_file"

          # Compute hashes via Nix evaluation
          hash_json=$(${nixBin} eval ".#sourcePins.${escapeShellArg name}" --json 2>/dev/null || true)
          if [ -z "$hash_json" ] || [ "$hash_json" = "{}" ]; then
            echo "ERROR: failed to compute hashes for $n" >&2
            echo "  Try: nix eval .#sourcePins.${escapeShellArg name}" >&2
            exit 1
          fi

          # Write sidecar atomically
          {
            echo "# Generated by nix-cache-pin source-pins — do not edit manually."
            echo "# Lock file:   $lock"
            echo "# Source pin:  $n"
            echo "# Updated:     $(date -u +%Y-%m-%dT%H:%M:%SZ)"
            echo "{"
            echo "$hash_json" | ${jqBin} -r 'to_entries[] | "  # \(.key[0:80])\n  \"\(.key)\" = \"\(.value)\";"'
            echo "}"
          } > "$output_file.tmp"

          if [ -f "$output_file" ] && cmp -s "$output_file.tmp" "$output_file"; then
            echo "  No changes — $(basename "$output_file") is current"
            rm -f "$output_file.tmp"
          else
            mv "$output_file.tmp" "$output_file"
            echo "  Updated $(basename "$output_file")"
          fi
        '';

      mkCoverageCheck = name: pin: let
        lockFileStorePath = builtins.toString pin.lockFile;
        flakeRoot = sourcePinsSelf.outPath;
        outputFileAbs = "${flakeRoot}/${pin.outputFile}";
      in
        pkgs.runCommand "cache-pin-source-pins-${name}-coverage" {
          nativeBuildInputs = with pkgs; [diffutils gnused ripgrep];
        } ''
          set -euo pipefail

          # Extract git sources from Cargo.lock
          rg 'source = "git\+' "${lockFileStorePath}" \
            | sed 's/.*source = "//;s/"$//' \
            | sed 's|^git+https://codeberg.org/|git+ssh://git@codeberg.org/|' \
            | sort > "$TMPDIR/lock_sources"

          # Extract keys from output sidecar
          if [ -f "${outputFileAbs}" ]; then
            rg '^\s+"git\+' "${outputFileAbs}" \
              | sed 's/^\s*"//;s/" =.*//' \
              | sed 's|^git+https://codeberg.org/|git+ssh://git@codeberg.org/|' \
              | sort > "$TMPDIR/sidecar_keys"
          else
            touch "$TMPDIR/sidecar_keys"
          fi

          # Check: lock sources NOT in sidecar
          comm -23 "$TMPDIR/lock_sources" "$TMPDIR/sidecar_keys" > "$TMPDIR/missing"
          if [[ -s "$TMPDIR/missing" ]]; then
            echo "ERROR: Cargo.lock has git sources without sidecar entries:" >&2
            while IFS= read -r line; do
              echo "  $line" >&2
            done < "$TMPDIR/missing"
            echo "" >&2
            echo "Fix: run 'nix run .#cache-pin-source-pins-${escapeShellArg name}'" >&2
            exit 1
          fi

          # Informational: stale entries
          comm -13 "$TMPDIR/lock_sources" "$TMPDIR/sidecar_keys" > "$TMPDIR/stale"
          if [[ -s "$TMPDIR/stale" ]]; then
            echo "NOTE: Sidecar has entries not in Cargo.lock (possibly stale):" >&2
            while IFS= read -r line; do
              echo "  $line" >&2
            done < "$TMPDIR/stale"
          fi

          touch "$out"
        '';

      updateScripts = mapAttrs mkUpdateScript cfg;

      allUpdateScript = pkgs.writeShellScriptBin "cache-pin-source-pins" ''
        set -euo pipefail
        results=()
        for n in ${concatStringsSep " " (builtins.attrNames cfg)}; do
          echo ""
          if "cache-pin-source-pins-$n"; then
            results+=("$n: OK")
          else
            results+=("$n: FAILED")
            echo "  ERROR: source-pin $n failed" >&2
          fi
        done
        echo ""
        echo "=== source-pins summary ==="
        printf '%s\n' "''${results[@]}"
      '';

      checkDrvs = mapAttrs mkCoverageCheck cfg;
    in {
      apps =
        mapAttrs' (name: drv:
          nameValuePair "cache-pin-source-pins-${name}" {
            type = "app";
            program = "${drv}/bin/cache-pin-source-pins-${name}";
          })
        updateScripts
        // {
          cache-pin-source-pins = {
            type = "app";
            program = "${allUpdateScript}/bin/cache-pin-source-pins";
          };
        };

      checks = checkDrvs;
    };
  };
}
